@startuml Wiederholung Objektdiagramme
object Leser

object "Hans Müller"
"Hans Müller" : Addresse = Bochum
"Hans Müller" : Geburtstag = 01.03.1995
"Hans Müller" : Ausleihe = 1
"Hans Müller" : Rückgabedatum = 20.05.2014

object "Else Wallersee"
"Else Wallersee" : Addresse = Dortmund
"Else Wallersee" : Geburtstag = 26.03.1948
"Else Wallersee" : Ausleihe = 2, 3
"Else Wallersee" : Rückgabedatum = 21.05.2014

Leser -- "Hans Müller"
Leser -- "Else Wallersee"
@enduml
