@startuml bungseinheit 1 Aufgabe 8

actor Antragsteller
participant Antrag
participant Versicherung

activate Antragsteller
activate Antrag

loop 10 Mal
    Antragsteller --> Antragsteller : hasMoreUnbetragteLeistungen()
    alt hasMoreUnbetragteLeistungen
        Antragsteller --> Antragsteller : getNextLeistung()
        Antragsteller --> Antrag : tryAddLeistung(nextLeistung)
        Antrag --> Versicherung : isErstattbar(leistung)
        activate Versicherung
        return
        deactivate Versicherung
        alt istErstattbar
            Antrag --> Antrag : addLeistung(leistung)
        end
    end
end

Antragsteller --> Antrag : getSumLeistungen()
activate Antrag
return sum

alt sum <= 1000
    Antragsteller --> Antrag : cancel()
else
    Antragsteller --> Antrag : submit()
end

alt Math.random() <= 0.5
    Antragsteller --> Antrag : setBemerkung("Bemerkung")
end
@enduml