@startuml Database 

entity f_authentication {
    * NutzerID (used as Primary Key)
    --
    * Kennung
    * Anbieter
    * Erstellt
    * Angemeldet
}

entity admin {
    * adminDocumentID
}

entity adminDocument{
    * isAdmin
}

entity appointments {
    * appointmentDocumentID
}

entity appointmentDocument {
    * description
    * nextOccurence
    * owner
    * repetiton
    * title
}


admin ||--|{ adminDocument
appointments ||--|{ appointmentDocument
appointmentDocument ||--|| f_authentication
f_authentication ||--|| adminDocument

@enduml