@startuml Software Architektur
interface "Cloud Firestore" as firestore


package "React App" as front{
    
    package "Components" as cmp{
    [Appointment]
    [NewAppointment]
    [Calendar]
    [Login]
    [ProfileScreen]
    [RegisterScreen]
    }

    front --> firestore

}

database "Backend" as backnd{
    backnd -- firestore
    [Authentication]
    [Appointments]
    [Admin]

@enduml